name: Deploy to GitHub Pages

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    permissions:
      contents: write
      
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          submodules: true  # Initialize and update submodules

      - name: Pull latest data from submodule
        run: git submodule update --remote --merge

      - name: Install dependencies
        run: npm install

      - name: Print package.json contents
        run: cat src/all-my-projects-data/package.json

      - name: List files in directory
        run: ls -la src/all-my-projects-data

      - name: Run build script
        run: |
          cd src/all-my-projects-data
          npm run build

      - name: Build the app
        run: npm run build_prod

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
